// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykmboynjqkilrxfbnzye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrbWJveW5qcWtpbHJ4ZmJuenllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjcwNjgsImV4cCI6MjA2MzYwMzA2OH0.RElW8GHmN0H32_M6ZpaHdIIZ2ugF6cH6C59DaN4pFQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);